
### Validates right username and password
POST http://10.88.74.4:3002/api/validate_user
content-type: application/x-www-form-urlencoded

username=natalia.figueroa
&password=Hola1234

### Airports retrieveving 50%

GET  http://10.88.74.4:3001/api/airports
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5hdGFsaWEuZmlndWVyb2EiLCJmaXJzdG5hbWUiOiJOYXRhbGlhIiwibGFzdG5hbWUiOiJGaWd1ZXJvYSIsImRpcmVjdGlvbiI6Ijo6ZmZmZjoxMC44OC43NS4yMTAiLCJpYXQiOjE3MDI1MzkwMjksImV4cCI6MTcwMjU1MzQyOX0.tNqiFIOJ96oBUpIV2UaEZ8cmFlDTl_A3agMyiLSdhTs

### Concrete Airport

GET  http://10.88.74.4:3001/api/airport/3725
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5hdGFsaWEuZmlndWVyb2EiLCJmaXJzdG5hbWUiOiJOYXRhbGlhIiwibGFzdG5hbWUiOiJGaWd1ZXJvYSIsImRpcmVjdGlvbiI6Ijo6ZmZmZjoxMC44OC43NS4yMTAiLCJpYXQiOjE3MDI1MzkwMjksImV4cCI6MTcwMjU1MzQyOX0.tNqiFIOJ96oBUpIV2UaEZ8cmFlDTl_A3agMyiLSdhTs

### Retrieving  arriving airport from origin

GET  http://10.88.74.4:3001/api/destination_airports/origin_airport/3725
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5hdGFsaWEuZmlndWVyb2EiLCJmaXJzdG5hbWUiOiJOYXRhbGlhIiwibGFzdG5hbWUiOiJGaWd1ZXJvYSIsImRpcmVjdGlvbiI6Ijo6ZmZmZjoxMC44OC43NS4yMTAiLCJpYXQiOjE3MDI1MzkwMjksImV4cCI6MTcwMjU1MzQyOX0.tNqiFIOJ96oBUpIV2UaEZ8cmFlDTl_A3agMyiLSdhTs


###Recuperacion de los aeropuertos de destino de un aeropuerto de salida concreto

GET  http://10.88.74.4:3001/api/flights/origin_airport/3725/destination_airport/1763
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5hdGFsaWEuZmlndWVyb2EiLCJmaXJzdG5hbWUiOiJOYXRhbGlhIiwibGFzdG5hbWUiOiJGaWd1ZXJvYSIsImRpcmVjdGlvbiI6Ijo6ZmZmZjoxMC44OC43NS4yMTAiLCJpYXQiOjE3MDI1MzkwMjksImV4cCI6MTcwMjU1MzQyOX0.tNqiFIOJ96oBUpIV2UaEZ8cmFlDTl_A3agMyiLSdhTs
